"""Build the standalone MoniToggle executables via PyInstaller (through uv).

    python build.py            # both
    python build.py gui        # tray app only
    python build.py cli        # command-line tool only (no GUI dependencies)

PyInstaller builds for the platform it runs on. The files are named like
the GitHub release assets, with platform and architecture, e.g.
dist/monitoggle-windows-x86_64.exe (tray app) and
dist/monitoggle-cli-windows-x86_64.exe, or dist/monitoggle-linux-x86_64
and dist/monitoggle-cli-linux-x86_64. The version (latest git tag, via `git describe`) is baked
into both; on Windows also into the file properties (version resource),
whose file description is also what notifications show as their source.
"""

import argparse
import platform
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
EXE_SUFFIX = ".exe" if sys.platform == "win32" else ""

# Reuse the runtime's names and git lookup; these modules only need the
# standard library, so this works without the project installed (CI runs
# `uv run --no-project`).
sys.path.insert(0, str(ROOT / "src"))
from monitoggle import APP_NAME, CLI_NAME, DISPLAY_NAME  # noqa: E402
from monitoggle.version import UNKNOWN, describe  # noqa: E402

GUI_NAME = APP_NAME
PRODUCT_NAME = DISPLAY_NAME
# File description in the Windows file properties. Windows also shows it as
# the source of the tray app's notifications.
DESCRIPTIONS = {GUI_NAME: PRODUCT_NAME, CLI_NAME: f"{PRODUCT_NAME} command-line tool"}

# Generated Windows version resources go here (gitignored).
BUILD_DIR = ROOT / "build"

# Never bundled into the CLI executable, even if the 'gui' extra happens to
# be installed in the environment it is built from.
GUI_ONLY_MODULES = ("monitoggle.gui", "PySide6", "shiboken6", "Xlib")

# Read by monitoggle.version in the built executables; only exists
# during a build (gitignored).
BUILD_VERSION_FILE = ROOT / "src" / "monitoggle" / "_build_version.py"


def run(*args: str) -> None:
    subprocess.run(args, cwd=ROOT, check=True)


# Names used for the architecture in file names (platform.machine() varies:
# AMD64 on Windows, x86_64 on Linux).
_ARCHITECTURES = {"amd64": "x86_64", "x86_64": "x86_64", "arm64": "arm64", "aarch64": "arm64"}


def platform_suffix() -> str:
    """E.g. "windows-x86_64" or "linux-x86_64", as in the release assets."""
    if sys.platform == "win32":
        system = "windows"
    elif sys.platform.startswith("linux"):
        system = "linux"
    else:
        system = sys.platform
    machine = platform.machine().lower()
    return f"{system}-{_ARCHITECTURES.get(machine, machine)}"


def output_name(name: str) -> str:
    """The executable's file name without extension, e.g.
    "monitoggle-windows-x86_64" for "monitoggle"."""
    return f"{name}-{platform_suffix()}"


# --- Windows version resource ------------------------------------------------------


def numeric_version(version: str) -> tuple[int, int, int, int]:
    """The four numbers Windows allows for a file version: major, minor and
    patch of the tag, then the commits since it (0 for a release build).

    "v1.2.3" -> (1, 2, 3, 0); "v1.2.3-4-gabc1234-dirty" -> (1, 2, 3, 4);
    "unknown" -> (0, 0, 0, 0)."""
    match = re.search(r"(\d+)\.(\d+)\.(\d+)", version)
    if match is None:
        return (0, 0, 0, 0)
    commits = re.search(r"-(\d+)-g[0-9a-f]+", version)
    major, minor, patch = (int(n) for n in match.groups())
    return (major, minor, patch, int(commits.group(1)) if commits else 0)


def copyright_line() -> str:
    """E.g. "Copyright (c) 2026 KolSmn", from LICENSE."""
    for line in (ROOT / "LICENSE").read_text(encoding="utf-8").splitlines():
        if line.startswith("Copyright"):
            return line.strip()
    return ""


def version_resource(name: str, version: str) -> str:
    """A PyInstaller --version-file for executable name: what Windows shows
    in the file properties (Details tab)."""
    numbers = numeric_version(version)
    strings = {
        "CompanyName": "",
        "FileDescription": DESCRIPTIONS[name],
        "FileVersion": ".".join(map(str, numbers)),
        "InternalName": name,
        "LegalCopyright": copyright_line(),
        "OriginalFilename": f"{output_name(name)}.exe",
        "ProductName": PRODUCT_NAME,
        "ProductVersion": version,  # the full git version, e.g. v1.2.3
    }
    # PyInstaller evaluates this file as Python; repr() quotes the values.
    table = ",\n          ".join(
        f"StringStruct({key!r}, {value!r})" for key, value in strings.items()
    )
    return f"""# Generated by build.py; do not edit or commit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numbers},
    prodvers={numbers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
          {table}
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def version_options(name: str, version: str) -> list[str]:
    """PyInstaller options that embed the version resource (Windows only)."""
    if sys.platform != "win32":
        return []
    path = BUILD_DIR / f"{name}-version.txt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(version_resource(name, version), encoding="utf-8")
    return ["--version-file", str(path)]


# --- Build ---------------------------------------------------------------------------


def pyinstaller(
    name: str,
    script: str,
    *options: str,
    version: str,
    extras: tuple[str, ...] = (),
) -> Path:
    extra_args = [arg for extra in extras for arg in ("--extra", extra)]
    filename = output_name(name)
    # "python -m PyInstaller" rather than the pyinstaller script: uv's script
    # launcher on Windows can fail to resolve its own path on some drives
    # ("uv trampoline failed to canonicalize script path").
    run(
        "uv",
        "run",
        *extra_args,
        "python",
        "-m",
        "PyInstaller",
        "--onefile",
        "--name",
        filename,
        "--clean",
        "--paths",
        "src",
        *version_options(name, version),
        *options,
        script,
    )
    return ROOT / "dist" / f"{filename}{EXE_SUFFIX}"


def build_cli(version: str) -> Path:
    # --inexact: don't uninstall the 'gui' extra from a dev environment; the
    # excludes below keep it out of the executable anyway.
    run("uv", "sync", "--inexact")
    excludes = [arg for mod in GUI_ONLY_MODULES for arg in ("--exclude-module", mod)]
    return pyinstaller(
        CLI_NAME, "src/monitoggle/__main__.py", "--console", *excludes, version=version
    )


def build_gui(version: str) -> Path:
    run("uv", "sync", "--inexact", "--extra", "gui")
    # --windowed: no console window for the tray app.
    return pyinstaller(
        GUI_NAME,
        "src/monitoggle/gui/__main__.py",
        "--windowed",
        version=version,
        extras=("gui",),
    )


BUILDERS = {"gui": build_gui, "cli": build_cli}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "targets", nargs="*", help="What to build: gui, cli (default: both)"
    )
    targets = parser.parse_args().targets or list(BUILDERS)
    unknown = [t for t in targets if t not in BUILDERS]
    if unknown:
        parser.error(f"unknown target(s): {', '.join(unknown)} (choose from gui, cli)")

    version = describe(ROOT)
    if version is None:
        print(f"warning: no git version found, building as '{UNKNOWN}'", file=sys.stderr)
        version = UNKNOWN
    print(f"Version: {version}")

    BUILD_VERSION_FILE.write_text(
        f"# Generated by build.py; do not edit or commit.\nVERSION = {version!r}\n",
        encoding="utf-8",
    )
    try:
        built = [BUILDERS[t](version) for t in dict.fromkeys(targets)]
    finally:
        # Running from source must ask git again, not see a stale version.
        BUILD_VERSION_FILE.unlink(missing_ok=True)
    print("Done:", ", ".join(str(p) for p in built))
    return 0


if __name__ == "__main__":
    sys.exit(main())
